//! Foolbox script generation and output parsing

use super::config::FoolboxConfig;
use crate::counterexample::StructuredCounterexample;
use crate::traits::{BackendError, VerificationStatus};
use dashprove_usl::ast::{ComparisonOp, Expr, Property};
use dashprove_usl::typecheck::TypedSpec;

/// Generate a Foolbox evaluation script from USL spec
pub fn generate_foolbox_script(
    spec: &TypedSpec,
    config: &FoolboxConfig,
) -> Result<String, BackendError> {
    let epsilon = extract_epsilon_from_spec(spec).unwrap_or(config.epsilon);
    let model_path = extract_model_path_from_spec(spec)
        .or_else(|| config.model_path.as_ref().map(|p| p.display().to_string()))
        .unwrap_or_else(|| "model.pt".to_string());

    let attack_class = config.attack_type.foolbox_class();
    let num_samples = config.num_samples;
    let steps = config.steps;

    Ok(format!(
        r#"#!/usr/bin/env python3
"""
Foolbox adversarial robustness evaluation script
Generated by DashProve
"""

import sys
import json
import numpy as np

try:
    import foolbox as fb
    import torch
    import torch.nn as nn
except ImportError as e:
    print(f"FOOLBOX_ERROR: Missing dependency: {{e}}")
    sys.exit(1)

def load_model(model_path: str):
    """Load a PyTorch model for Foolbox evaluation."""
    try:
        model = torch.load(model_path, map_location='cpu')
        if isinstance(model, dict):
            print("FOOLBOX_ERROR: Model is a state dict, need full model")
            return None
        model.eval()
        return model
    except Exception as e:
        print(f"FOOLBOX_ERROR: Failed to load model: {{e}}")
        return None

def create_test_data(num_samples: int = {num_samples}):
    """Create synthetic test data for evaluation."""
    np.random.seed(42)
    x_test = np.random.rand(num_samples, 3, 32, 32).astype(np.float32)
    y_test = np.random.randint(0, 10, num_samples)
    return x_test, y_test

def main():
    model_path = "{model_path}"
    epsilon = {epsilon}
    num_samples = {num_samples}
    steps = {steps}

    # Try to load model (or use dummy for testing)
    model = load_model(model_path)

    if model is None:
        # Use a simple test model
        model = nn.Sequential(
            nn.Flatten(),
            nn.Linear(3 * 32 * 32, 256),
            nn.ReLU(),
            nn.Linear(256, 10)
        )
        model.eval()
        print("FOOLBOX_INFO: Using synthetic test model")

    # Create Foolbox model wrapper
    fmodel = fb.PyTorchModel(model, bounds=(0, 1))

    # Generate test data
    x_test, y_test = create_test_data(num_samples)
    images = torch.from_numpy(x_test)
    labels = torch.from_numpy(y_test)

    # Get clean accuracy
    clean_preds = fmodel(images).argmax(axis=-1).numpy()
    clean_accuracy = (clean_preds == y_test).mean()

    # Create attack
    attack = fb.attacks.{attack_class}()

    # Run attack
    raw_advs, clipped_advs, is_adv = attack(fmodel, images, labels, epsilons=[epsilon])

    # Get results for our epsilon
    advs = clipped_advs[0]
    success = is_adv[0]

    # Calculate adversarial accuracy
    adv_preds = fmodel(advs).argmax(axis=-1).numpy()
    adv_accuracy = (adv_preds == y_test).mean()

    # Find adversarial examples
    adv_indices = np.where(success.numpy())[0]

    # Calculate perturbation stats
    perturbations = (advs - images).numpy()
    max_perturbation = float(np.max(np.abs(perturbations)))
    mean_perturbation = float(np.mean(np.abs(perturbations)))

    # Calculate metrics
    robust_accuracy = float(adv_accuracy)
    attack_success_rate = float(success.float().mean().item())

    # Output results
    print("FOOLBOX_RESULT_START")
    result = {{
        "clean_accuracy": float(clean_accuracy),
        "adversarial_accuracy": float(adv_accuracy),
        "robust_accuracy": robust_accuracy,
        "attack_success_rate": attack_success_rate,
        "num_adversarial_examples": int(len(adv_indices)),
        "max_perturbation": max_perturbation,
        "mean_perturbation": mean_perturbation,
        "epsilon": float(epsilon),
        "attack_type": "{attack_class}",
        "num_samples": int(num_samples)
    }}

    # Add first adversarial example if found
    if len(adv_indices) > 0:
        idx = adv_indices[0]
        result["adversarial_example"] = {{
            "original_input": images[idx].flatten()[:10].tolist(),
            "adversarial_input": advs[idx].flatten()[:10].tolist(),
            "original_prediction": int(clean_preds[idx]),
            "adversarial_prediction": int(adv_preds[idx]),
            "true_label": int(y_test[idx]),
            "perturbation_norm": float(np.linalg.norm(perturbations[idx].flatten(), ord=np.inf))
        }}

    print(json.dumps(result, indent=2))
    print("FOOLBOX_RESULT_END")

    # Print summary
    print(f"\\nFOOLBOX_SUMMARY: Clean accuracy: {{clean_accuracy:.2%}}, Robust accuracy: {{robust_accuracy:.2%}}")
    print(f"FOOLBOX_SUMMARY: Attack success rate: {{attack_success_rate:.2%}}, Found {{len(adv_indices)}} adversarial examples")

    # Determine robustness status
    if attack_success_rate < 0.01:
        print("FOOLBOX_STATUS: ROBUST")
    elif attack_success_rate < 0.10:
        print("FOOLBOX_STATUS: PARTIALLY_ROBUST")
    else:
        print("FOOLBOX_STATUS: NOT_ROBUST")

if __name__ == "__main__":
    main()
"#
    ))
}

/// Extract epsilon value from USL spec properties
fn extract_epsilon_from_spec(spec: &TypedSpec) -> Option<f64> {
    for prop in &spec.spec.properties {
        let expr = match prop {
            Property::Invariant(inv) => Some(&inv.body),
            Property::Theorem(thm) => Some(&thm.body),
            Property::Security(sec) => Some(&sec.body),
            Property::Probabilistic(prob) => Some(&prob.condition),
            _ => None,
        };
        if let Some(e) = expr {
            if let Some(eps) = extract_epsilon(e) {
                return Some(eps);
            }
        }
    }
    None
}

/// Extract epsilon from expression
fn extract_epsilon(expr: &Expr) -> Option<f64> {
    match expr {
        Expr::Compare(lhs, op, rhs) => {
            if let Expr::Var(name) = lhs.as_ref() {
                let lower = name.to_lowercase();
                if (lower.contains("epsilon") || lower == "eps")
                    && matches!(op, ComparisonOp::Le | ComparisonOp::Lt)
                {
                    return extract_numeric_value(rhs);
                }
            }
            if let Expr::Var(name) = rhs.as_ref() {
                let lower = name.to_lowercase();
                if (lower.contains("epsilon") || lower == "eps")
                    && matches!(op, ComparisonOp::Ge | ComparisonOp::Gt)
                {
                    return extract_numeric_value(lhs);
                }
            }
            if matches!(op, ComparisonOp::Le | ComparisonOp::Lt) {
                if let Some(val) = extract_numeric_value(rhs) {
                    if val > 0.0 && val < 1.0 {
                        return Some(val);
                    }
                }
            }
            extract_epsilon(lhs).or_else(|| extract_epsilon(rhs))
        }
        Expr::And(lhs, rhs) | Expr::Or(lhs, rhs) | Expr::Implies(lhs, rhs) => {
            extract_epsilon(lhs).or_else(|| extract_epsilon(rhs))
        }
        Expr::Not(inner) | Expr::Neg(inner) => extract_epsilon(inner),
        Expr::Binary(lhs, _, rhs) => extract_epsilon(lhs).or_else(|| extract_epsilon(rhs)),
        Expr::ForAll { body, .. }
        | Expr::Exists { body, .. }
        | Expr::ForAllIn { body, .. }
        | Expr::ExistsIn { body, .. } => extract_epsilon(body),
        Expr::FieldAccess(obj, _) => extract_epsilon(obj),
        Expr::MethodCall { receiver, args, .. } => {
            extract_epsilon(receiver).or_else(|| args.iter().find_map(extract_epsilon))
        }
        Expr::App(_, args) => args.iter().find_map(extract_epsilon),
        Expr::Var(_) | Expr::Int(_) | Expr::Float(_) | Expr::String(_) | Expr::Bool(_) => None,
    }
}

fn extract_numeric_value(expr: &Expr) -> Option<f64> {
    match expr {
        Expr::Float(f) => Some(*f),
        Expr::Int(i) => Some(*i as f64),
        Expr::Neg(inner) => extract_numeric_value(inner).map(|v| -v),
        _ => None,
    }
}

fn extract_model_path_from_spec(spec: &TypedSpec) -> Option<String> {
    for typedef in &spec.spec.types {
        for field in &typedef.fields {
            let lower = field.name.to_lowercase();
            if lower.contains("model") || lower.contains("network") {
                if let dashprove_usl::ast::Type::Named(name) = &field.ty {
                    if name.to_lowercase().contains("path")
                        || name.to_lowercase().contains("string")
                    {
                        return Some(field.name.clone());
                    }
                }
            }
        }
    }
    None
}

/// Parse Foolbox script output
pub fn parse_foolbox_output(
    stdout: &str,
    stderr: &str,
) -> (VerificationStatus, Option<StructuredCounterexample>) {
    if stdout.contains("FOOLBOX_ERROR:") || stderr.contains("FOOLBOX_ERROR:") {
        let error_msg = stdout
            .lines()
            .chain(stderr.lines())
            .find(|l| l.contains("FOOLBOX_ERROR:"))
            .map(|l| l.replace("FOOLBOX_ERROR:", "").trim().to_string())
            .unwrap_or_else(|| "Unknown Foolbox error".to_string());

        return (VerificationStatus::Unknown { reason: error_msg }, None);
    }

    if let Some(json_str) = extract_json_result(stdout) {
        if let Ok(result) = serde_json::from_str::<serde_json::Value>(&json_str) {
            let attack_success_rate = result["attack_success_rate"].as_f64().unwrap_or(1.0);
            let robust_accuracy = result["robust_accuracy"].as_f64().unwrap_or(0.0);

            let counterexample =
                crate::counterexample::build_adversarial_attack_counterexample(&result, "Foolbox");

            if attack_success_rate < 0.01 {
                return (VerificationStatus::Proven, None);
            } else if attack_success_rate < 0.10 {
                return (
                    VerificationStatus::Partial {
                        verified_percentage: robust_accuracy * 100.0,
                    },
                    counterexample,
                );
            } else {
                return (VerificationStatus::Disproven, counterexample);
            }
        }
    }

    // Fallback
    if stdout.contains("FOOLBOX_STATUS: ROBUST") {
        (VerificationStatus::Proven, None)
    } else if stdout.contains("FOOLBOX_STATUS: PARTIALLY_ROBUST") {
        (
            VerificationStatus::Partial {
                verified_percentage: 90.0,
            },
            None,
        )
    } else if stdout.contains("FOOLBOX_STATUS: NOT_ROBUST") {
        (VerificationStatus::Disproven, None)
    } else {
        (
            VerificationStatus::Unknown {
                reason: "Could not parse Foolbox output".to_string(),
            },
            None,
        )
    }
}

fn extract_json_result(output: &str) -> Option<String> {
    let start_marker = "FOOLBOX_RESULT_START";
    let end_marker = "FOOLBOX_RESULT_END";

    if let Some(start) = output.find(start_marker) {
        let after_start = &output[start + start_marker.len()..];
        if let Some(end) = after_start.find(end_marker) {
            return Some(after_start[..end].trim().to_string());
        }
    }
    None
}
