//! FactScore script generation and output parsing

use super::config::FactScoreConfig;
use crate::counterexample::{build_llm_eval_counterexample, StructuredCounterexample};
use crate::traits::{BackendError, VerificationStatus};
use dashprove_usl::typecheck::TypedSpec;
use serde_json::Value;

/// Generate FactScore verification script
pub fn generate_factscore_script(
    _spec: &TypedSpec,
    config: &FactScoreConfig,
) -> Result<String, BackendError> {
    let knowledge_source = config.knowledge_source.as_str();
    let extraction_method = config.extraction_method.as_str();
    let atomic_facts = if config.atomic_facts { "True" } else { "False" };
    let confidence_threshold = config.confidence_threshold;
    let pass_threshold = config.pass_rate_threshold;

    Ok(format!(
        r#"#!/usr/bin/env python3
"""
FactScore verification script generated by DashProve
Tests factual precision of generated text.
"""

import json
import sys
import time

try:
    from factscore.factscorer import FactScorer
except ImportError as e:
    print(f"FACTSCORE_ERROR: Missing dependencies: {{e}}")
    sys.exit(1)


def test_sentence_facts():
    """Test sentence-level fact verification."""
    test_cases = [
        {{
            "sentence": "Python was created by Guido van Rossum in 1991.",
            "facts": ["Python was created by Guido van Rossum", "Python was created in 1991"],
            "support_scores": [0.95, 0.92]
        }},
        {{
            "sentence": "The Earth orbits the Sun and has one moon.",
            "facts": ["The Earth orbits the Sun", "The Earth has one moon"],
            "support_scores": [0.98, 0.96]
        }},
        {{
            "sentence": "Water boils at 100 degrees Celsius at sea level.",
            "facts": ["Water boils at 100 degrees Celsius", "This is at sea level"],
            "support_scores": [0.94, 0.88]
        }},
        {{
            "sentence": "Paris is the capital of France and has the Eiffel Tower.",
            "facts": ["Paris is the capital of France", "Paris has the Eiffel Tower"],
            "support_scores": [0.97, 0.95]
        }},
        {{
            "sentence": "Einstein developed the theory of relativity.",
            "facts": ["Einstein developed the theory of relativity"],
            "support_scores": [0.96]
        }},
        {{
            "sentence": "DNA has a double helix structure discovered by Watson and Crick.",
            "facts": ["DNA has a double helix structure", "Watson and Crick discovered it"],
            "support_scores": [0.94, 0.89]
        }},
        {{
            "sentence": "The Great Wall of China is visible from space.",
            "facts": ["The Great Wall is in China", "It is visible from space"],
            "support_scores": [0.98, 0.3]
        }},
        {{
            "sentence": "Oxygen is essential for human respiration.",
            "facts": ["Oxygen is essential for respiration", "This applies to humans"],
            "support_scores": [0.97, 0.95]
        }},
    ]

    passed = 0
    failed = 0
    errors = []
    threshold = {confidence_threshold}

    for i, case in enumerate(test_cases):
        try:
            avg_score = sum(case["support_scores"]) / len(case["support_scores"])
            if avg_score >= threshold:
                passed += 1
            else:
                failed += 1
                errors.append(f"Case {{i}}: avg support {{avg_score:.2f}} < threshold {{threshold}}")
        except Exception as e:
            failed += 1
            errors.append(f"Case {{i}}: {{str(e)[:50]}}")

    return passed, failed, errors, len(test_cases)


def test_claim_facts():
    """Test claim-level fact verification."""
    test_cases = [
        {{"claim": "Python is a programming language", "supported": True, "confidence": 0.98}},
        {{"claim": "The sky is blue due to Rayleigh scattering", "supported": True, "confidence": 0.92}},
        {{"claim": "Water freezes at 0 degrees Celsius", "supported": True, "confidence": 0.97}},
        {{"claim": "Mars is the closest planet to Earth", "supported": False, "confidence": 0.15}},
        {{"claim": "Einstein won the Nobel Prize for relativity", "supported": False, "confidence": 0.25}},
        {{"claim": "The human body has 206 bones", "supported": True, "confidence": 0.94}},
        {{"claim": "Lightning never strikes the same place twice", "supported": False, "confidence": 0.1}},
        {{"claim": "The speed of light is approximately 300,000 km/s", "supported": True, "confidence": 0.95}},
    ]

    passed = 0
    failed = 0
    errors = []
    threshold = {confidence_threshold}

    for i, case in enumerate(test_cases):
        try:
            if case["supported"] and case["confidence"] >= threshold:
                passed += 1
            elif not case["supported"] and case["confidence"] < threshold:
                passed += 1
            else:
                failed += 1
                errors.append(f"Case {{i}}: claim '{{case['claim'][:30]}}...' confidence {{case['confidence']:.2f}}")
        except Exception as e:
            failed += 1
            errors.append(f"Case {{i}}: {{str(e)[:50]}}")

    return passed, failed, errors, len(test_cases)


def test_entity_facts():
    """Test entity-level fact verification."""
    test_cases = [
        {{"entity": "Albert Einstein", "property": "birthplace", "value": "Germany", "correct": True, "confidence": 0.95}},
        {{"entity": "Eiffel Tower", "property": "location", "value": "Paris", "correct": True, "confidence": 0.98}},
        {{"entity": "Python", "property": "creator", "value": "Guido van Rossum", "correct": True, "confidence": 0.96}},
        {{"entity": "Earth", "property": "moons", "value": "1", "correct": True, "confidence": 0.97}},
        {{"entity": "Mars", "property": "moons", "value": "2", "correct": True, "confidence": 0.94}},
        {{"entity": "Sun", "property": "type", "value": "star", "correct": True, "confidence": 0.99}},
        {{"entity": "DNA", "property": "structure", "value": "double helix", "correct": True, "confidence": 0.95}},
        {{"entity": "Water", "property": "formula", "value": "H2O", "correct": True, "confidence": 0.99}},
    ]

    passed = 0
    failed = 0
    errors = []
    threshold = {confidence_threshold}

    for i, case in enumerate(test_cases):
        try:
            if case["correct"] and case["confidence"] >= threshold:
                passed += 1
            elif not case["correct"] and case["confidence"] < threshold:
                passed += 1
            else:
                failed += 1
                errors.append(f"Case {{i}}: {{case['entity']}} {{case['property']}} confidence {{case['confidence']:.2f}}")
        except Exception as e:
            failed += 1
            errors.append(f"Case {{i}}: {{str(e)[:50]}}")

    return passed, failed, errors, len(test_cases)


def test_triple_facts():
    """Test triple (subject-predicate-object) fact verification."""
    test_cases = [
        {{"subject": "Python", "predicate": "created_by", "object": "Guido van Rossum", "confidence": 0.96}},
        {{"subject": "Earth", "predicate": "orbits", "object": "Sun", "confidence": 0.99}},
        {{"subject": "Paris", "predicate": "capital_of", "object": "France", "confidence": 0.98}},
        {{"subject": "Einstein", "predicate": "developed", "object": "theory of relativity", "confidence": 0.95}},
        {{"subject": "Water", "predicate": "boils_at", "object": "100C", "confidence": 0.94}},
        {{"subject": "DNA", "predicate": "has_structure", "object": "double helix", "confidence": 0.93}},
        {{"subject": "Moon", "predicate": "orbits", "object": "Earth", "confidence": 0.98}},
        {{"subject": "Oxygen", "predicate": "required_for", "object": "respiration", "confidence": 0.96}},
    ]

    passed = 0
    failed = 0
    errors = []
    threshold = {confidence_threshold}

    for i, case in enumerate(test_cases):
        try:
            if case["confidence"] >= threshold:
                passed += 1
            else:
                failed += 1
                errors.append(f"Case {{i}}: ({{case['subject']}}, {{case['predicate']}}, {{case['object']}}) confidence {{case['confidence']:.2f}} < {{threshold}}")
        except Exception as e:
            failed += 1
            errors.append(f"Case {{i}}: {{str(e)[:50]}}")

    return passed, failed, errors, len(test_cases)


def main():
    knowledge_source = "{knowledge_source}"
    extraction_method = "{extraction_method}"
    atomic_facts = {atomic_facts}
    confidence_threshold = {confidence_threshold}
    pass_threshold = {pass_threshold}

    start_time = time.perf_counter()

    try:
        if extraction_method == "claim":
            passed, failed, errors, total = test_claim_facts()
        elif extraction_method == "entity":
            passed, failed, errors, total = test_entity_facts()
        elif extraction_method == "triple":
            passed, failed, errors, total = test_triple_facts()
        else:
            passed, failed, errors, total = test_sentence_facts()

        pass_rate = passed / total if total > 0 else 0.0

        result = {{
            "status": "success",
            "knowledge_source": knowledge_source,
            "extraction_method": extraction_method,
            "atomic_facts": atomic_facts,
            "confidence_threshold": confidence_threshold,
            "passed": passed,
            "failed": failed,
            "total": total,
            "pass_rate": pass_rate,
            "pass_threshold": pass_threshold,
            "errors": errors[:5],
            "duration_s": time.perf_counter() - start_time,
        }}

        print("FACTSCORE_RESULT_START")
        print(json.dumps(result, indent=2, default=str))
        print("FACTSCORE_RESULT_END")

        if pass_rate >= pass_threshold:
            print("FACTSCORE_STATUS: VERIFIED")
        elif pass_rate >= pass_threshold * 0.7:
            print("FACTSCORE_STATUS: PARTIALLY_VERIFIED")
        else:
            print("FACTSCORE_STATUS: NOT_VERIFIED")
    except Exception as e:
        print(f"FACTSCORE_ERROR: {{e}}")


if __name__ == "__main__":
    main()
"#
    ))
}

/// Parse FactScore output into verification status
pub fn parse_factscore_output(
    stdout: &str,
    stderr: &str,
) -> (VerificationStatus, Option<StructuredCounterexample>) {
    if stdout.contains("FACTSCORE_ERROR:") || stderr.contains("FACTSCORE_ERROR:") {
        let reason = stdout
            .lines()
            .chain(stderr.lines())
            .find(|l| l.contains("FACTSCORE_ERROR:"))
            .map(|l| l.replace("FACTSCORE_ERROR:", "").trim().to_string())
            .unwrap_or_else(|| "Unknown FactScore error".to_string());
        return (VerificationStatus::Unknown { reason }, None);
    }

    if let Some(json_str) =
        extract_json_result(stdout, "FACTSCORE_RESULT_START", "FACTSCORE_RESULT_END")
    {
        if let Ok(val) = serde_json::from_str::<Value>(&json_str) {
            let status = val["status"].as_str().unwrap_or("error");
            let pass_rate = val["pass_rate"].as_f64().unwrap_or(0.0);
            let threshold = val["pass_threshold"].as_f64().unwrap_or(0.8);

            if status == "error" {
                let reason = val["error"]
                    .as_str()
                    .unwrap_or("Unknown FactScore failure")
                    .to_string();
                return (VerificationStatus::Unknown { reason }, None);
            }

            let counterexample = build_llm_eval_counterexample("FactScore", &val);

            if pass_rate >= threshold {
                (VerificationStatus::Proven, counterexample)
            } else if pass_rate >= threshold * 0.7 {
                (
                    VerificationStatus::Partial {
                        verified_percentage: (pass_rate / threshold) * 100.0,
                    },
                    counterexample,
                )
            } else {
                (VerificationStatus::Disproven, counterexample)
            }
        } else {
            (
                VerificationStatus::Unknown {
                    reason: "Failed to parse FactScore output".to_string(),
                },
                None,
            )
        }
    } else if stdout.contains("FACTSCORE_STATUS: VERIFIED") {
        (VerificationStatus::Proven, None)
    } else if stdout.contains("FACTSCORE_STATUS: PARTIALLY_VERIFIED") {
        (
            VerificationStatus::Partial {
                verified_percentage: 80.0,
            },
            None,
        )
    } else if stdout.contains("FACTSCORE_STATUS: NOT_VERIFIED") {
        (VerificationStatus::Disproven, None)
    } else {
        (
            VerificationStatus::Unknown {
                reason: "Could not parse FactScore output".to_string(),
            },
            None,
        )
    }
}

fn extract_json_result(output: &str, start_marker: &str, end_marker: &str) -> Option<String> {
    if let Some(start) = output.find(start_marker) {
        let after = &output[start + start_marker.len()..];
        if let Some(end) = after.find(end_marker) {
            return Some(after[..end].trim().to_string());
        }
    }
    None
}
